/** Copyright ©2025 Baragaun, Inc. - All rights reserved **/
import { GraphqlType } from '../../../../enums.js'
import { TypeGraphqlClass } from '../../../../types.js'

const sidUserDevice: TypeGraphqlClass = {
  name: 'SidUserDevice',
  graphqlType: GraphqlType.ObjectType,
  extends: 'BaseModel',
  path: 'src/services/secureId/types/classes/SidUserDevice.ts',
  dbCollectionName: 'user-devices',
  active: true,
  attributes: [
    { name: 'userId', dataType: 'id', optional: false },
    { name: 'deviceUuid', dataType: 'string', default: '\'\'' },
    { name: 'deviceType', dataType: 'string', optional: true },
    { name: 'trusted', dataType: 'boolean', default: 'false' },
    { name: 'phoneNumber', dataType: 'string', optional: true },
    { name: 'phoneNumberUpdatedAt', dataType: 'date', optional: true },
    { name: 'isPhoneNumberVerified', dataType: 'boolean', default: 'false' },
    { name: 'brand', dataType: 'string', optional: true },
    { name: 'model', dataType: 'string', optional: true },
    { name: 'isTablet', dataType: 'boolean', default: 'false' },
    { name: 'screenWidth', dataType: 'integer', default: '0' },
    { name: 'screenHeight', dataType: 'integer', default: '0' },
    { name: 'os', dataType: 'string', optional: true },
    { name: 'osVersion', dataType: 'string', optional: true },
    { name: 'timezone', dataType: 'string', optional: true },
    { name: 'ipAddress', dataType: 'string', optional: true },
    { name: 'consumer', dataType: 'string', optional: true },
    { name: 'consumerVersion', dataType: 'string', optional: true },
    { name: 'acceptedLanguage', dataType: 'string', optional: true },
    { name: 'locale', dataType: 'string', optional: true },
    { name: 'countryCode', dataType: 'string', optional: true },
    { name: 'appVersion', dataType: 'string', optional: true },
    { name: 'signedInAt', dataType: 'date', optional: true },
    { name: 'signedOutAt', dataType: 'date', optional: true },
    { name: 'sessionStartedAt', dataType: 'date', optional: true },
    { name: 'sessionEndedAt', dataType: 'date', optional: true },
    { name: 'authType', dataType: 'AuthType', optional: true },
    { name: 'identityProvider', dataType: 'IdentityProvider', optional: true },
    { name: 'oauthFederatedProvider', dataType: 'FederatedIdentityProvider', optional: true },
    { name: 'oauthUserId', dataType: 'string', optional: true },
    { name: 'oauthDelegateUserId', dataType: 'string', optional: true },
    { name: 'oauthProfileUrl', dataType: 'string', optional: true },
    { name: 'oauthToken', dataType: 'string', optional: true },
    { name: 'oauthTokenCreatedAt', dataType: 'date', optional: true },
    { name: 'oauthTokenExpiresAt', dataType: 'date', optional: true },
    { name: 'oauthRefreshToken', dataType: 'string', optional: true },
    { name: 'oauthRefreshTokenCreatedAt', dataType: 'date', optional: true },
    { name: 'oauthRefreshTokenExpiresAt', dataType: 'date', optional: true },
    { name: 'pushNotificationToken', dataType: 'string', optional: true },
    { name: 'trustedAt', dataType: 'date', optional: true },
  ]
}

export default sidUserDevice
