export const UploadedAssetSchema = {
  title: 'UploadedAsset',
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: {
      type: 'string',
      maxLength: 32,
    },
    adminNotes: {
      type: 'string',
      nullable: true,
    },
    metadata: {
      type: 'object',
      properties: {
        updatedAt: {
          type: 'string',
          format: 'date-time',
          nullable: true,
        },
      },
      nullable: true,
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
    },
    createdBy: {
      type: 'string',
      maxLength: 32,
      nullable: true,
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    updatedBy: {
      type: 'string',
      maxLength: 32,
      nullable: true,
    },
    deletedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    deletedBy: {
      type: 'string',
      maxLength: 32,
      nullable: true,
    },
    ownerId: {
      type: 'string',
      maxLength: 32,
    },
    ownerModelType: {
      type: 'string',
      enum: [
        'AcademicExperience',
        'BusinessExperience',
        'Company',
        'DataDeletionRecord',
        'MentorBoard',
        'MentoringSession',
        'UserInbox',
        'UserMetadata',
        'UserPreferences',
        'AdminTask',
        'UploadedAsset',
        'Channel',
        'ChannelInbox',
        'ChannelInvitation',
        'ChannelMessage',
        'ChannelParticipant',
        'ContentStatus',
        'Contact',
        'Option',
        'ContentTag',
        'AppliedGroupRule',
        'Group',
        'GroupMembership',
        'GroupRule',
        'GroupRuleConfig',
        'MastercardBank',
        'SupportChannelConfig',
        'Match',
        'MatchProfile',
        'MatchingEngine',
        'UserSearch',
        'Notification',
        'NotificationTemplate',
        'Mm2Integration',
        'Mm2Synchronization',
        'Mm2SynchronizationResultItem',
        'ModerationConcern',
        'ApiAuthInfo',
        'MultiStepAction',
        'MyUser',
        'ServiceRequest',
        'User',
        'UserDevice',
        'TrackingEvent',
        'UserTracking',
        'Training',
        'TrainingContentPage',
        'TrainingSession',
        'unset',
      ],
    },
    assetType: {
      type: 'string',
      enum: ['unset', 'avatar', 'profileHeroImage'],
    },
    hostingService: {
      type: 'string',
      enum: ['s3', 'unset'],
    },
    url: {
      type: 'string',
      nullable: true,
    },
    path: {
      type: 'string',
      nullable: true,
    },
    s3Bucket: {
      type: 'string',
      nullable: true,
    },
    s3Key: {
      type: 'string',
      nullable: true,
    },
    mimeType: {
      type: 'string',
      nullable: true,
    },
    uploadUrl: {
      type: 'string',
      nullable: true,
    },
    uploadUrlExpiresAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    uploadedAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
    expiresAt: {
      type: 'string',
      format: 'date-time',
      nullable: true,
    },
  },
  required: ['id'],
};
