export default `
query Q {
   findMyWallet {
    id
    adminNotes
    createdAt
    createdBy
    updatedAt
    updatedBy
    deletedAt
    deletedBy
    items {
      id
      adminNotes
      createdAt
      createdBy
      updatedAt
      updatedBy
      deletedAt
      deletedBy
      walletId
      productId
      purchaseOrderItemId
      vendorId
      name
      price
      initialBalance
      balance
      code
      hasBarcode
      barcodeFormat
      pin
      source
      imageSourceFront
      imageSourceBack
      referenceUrl
      termsEn
      termsUrl
      instructionsEn
      instructionsUrl
      sortIndex
      issuedAt
      expiresAt
      balanceUpdatedAt
      archivedAt
    }
  }
}
`;
