import { BaseModel } from './BaseModel.js';
import { LabeledStringValue } from './LabeledStringValue.js';
import { AppFeature, UiLanguage, UserRole } from '../enums.js';
import { Model } from './Model.js';
import { UserBlock } from './UserBlock.js';
import { UserMetadata } from './UserMetadata.js';
import { UserPreferences } from './UserPreferences.js';
export declare abstract class SidUser extends BaseModel implements Model {
    firstName?: string | null;
    lastName?: string | null;
    userHandle?: string | null;
    phoneNumber?: string | null;
    phoneNumberUpdatedAt?: string | null;
    isPhoneNumberVerified: boolean;
    email?: string | null;
    emailUpdatedAt?: string | null;
    isEmailVerified: boolean;
    genderTextId?: string | null;
    cityOfResidence?: string | null;
    regionOfResidence?: string | null;
    countryOfResidenceTextId?: string | null;
    postalCode?: string | null;
    avatarUrl?: string | null;
    websites?: LabeledStringValue[] | null;
    inviteCode?: string | null;
    passwordHash?: string | null;
    preferredLanguageTextId?: string | null;
    spokenLanguagesTextIds: string[];
    selectedUiLanguageTextId?: UiLanguage | null;
    fallbackUiLanguageTextId?: UiLanguage | null;
    discoverable?: boolean | null;
    roles: UserRole[];
    appFeatures?: AppFeature[] | null;
    source?: string | null;
    timezone?: string | null;
    preferences?: UserPreferences | null;
    trustLevel: number;
    userBlocks?: UserBlock[] | null;
    metadata?: UserMetadata | null;
    termsAndConditionsAcceptedAt?: string | null;
    optIntoNewsletter?: boolean | null;
    onboardingStage?: string | null;
    isTestUser?: boolean | null;
    signedInAt?: string | null;
    signedOutAt?: string | null;
    latestActivityAt?: string | null;
    inactivatedAt?: string | null;
    inactivatedBy?: string | null;
    suspendedAt?: string | null;
    suspendedBy?: string | null;
    anonymizedAt?: string | null;
    protected constructor(attributes?: Partial<SidUser>);
}
