import { LabeledStringValue } from './LabeledStringValue.js';
import { UserBlock } from './UserBlock.js';
import { UserRole } from '../enums.js';
import { AcademicExperience, BusinessExperience, MenteesGroupMembership, MentorsGroupMembership } from '../fsdata/gql/graphql.js';
import { IGroupMembership } from '../types/IGroupMembership.js';
export declare class UserListItem {
    id: string;
    createdAt: string;
    updatedAt?: string | null;
    deletedAt?: string | null;
    userHandle?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    avatarUrl?: string | null;
    genderTextId?: string | null;
    websites?: LabeledStringValue[] | null;
    preferredLanguageTextId?: string | null;
    spokenLanguagesTextIds: string[];
    countryOfResidenceTextId?: string | null;
    regionOfResidence?: string | null;
    cityOfResidence?: string | null;
    timezone?: string | null;
    roles: UserRole[];
    discoverable?: boolean | null;
    trustLevel: number;
    userBlocks?: UserBlock[] | null;
    latestActivityAt?: string | null;
    inactivatedAt?: string | null;
    suspendedAt?: string | null;
    seeksHelp?: boolean | null;
    offersHelp?: boolean | null;
    yearsManagementExperience?: number | null;
    yearsOwnershipExperience?: number | null;
    academicExperiences?: AcademicExperience[] | null;
    businessExperiences?: BusinessExperience[] | null;
    isOnVacation?: boolean | null;
    mentor?: MentorsGroupMembership | null;
    mentee?: MenteesGroupMembership | null;
    groupMemberships: IGroupMembership[];
    constructor(attributes?: Partial<UserListItem>);
    static get searchFields(): string[];
}
