import { BaseModel } from './BaseModel.js';
import { BarcodeType, ProductType, WalletItemSource } from '../enums.js';
export declare class WalletItem extends BaseModel {
    walletId: string;
    productId: string;
    purchaseOrderItemId: string;
    brandId: string;
    productType: ProductType;
    name: string;
    price: number;
    initialBalance: number;
    balance: number;
    code?: string | null;
    hasBarcode?: boolean | null;
    barcodeFormat?: BarcodeType | null;
    pin?: string | null;
    source?: WalletItemSource | null;
    imageSourceFront?: string | null;
    imageSourceBack?: string | null;
    referenceUrl?: string | null;
    termsEn?: string | null;
    termsUrl?: string | null;
    instructionsEn?: string | null;
    instructionsUrl?: string | null;
    sortIndex: number;
    issuedAt?: string | null;
    expiresAt?: string | null;
    balanceUpdatedAt?: string | null;
    transferStartedAt?: string | null;
    transferAcceptedAt?: string | null;
    archivedAt?: string | null;
    constructor(attributes?: Partial<WalletItem>);
}
