const baseModel = {
    id: true,
    createdAt: true,
    createdBy: true,
    updatedAt: true,
    updatedBy: true,
    deletedAt: true,
    deletedBy: true,
};
const channel = {
    ...baseModel,
    name: true,
    topic: true,
    description: true,
    tags: true,
    channelType: true,
    maxSeq: true,
    lastLiveSeq: true,
    userIds: true,
    // metadata: {
    //   channelInvitationAccepted: true,
    //   messagesSentByCreatorCount: true,
    //   messagesSentByFirstParticipantCount: true,
    //   updatedAt: true,
    // },
    adminNotes: true,
    pausedAt: true,
    pausedBy: true,
    suspendedAt: true,
    suspendedBy: true,
    lockedAt: true,
    lockedBy: true,
    archivedAt: true,
    archivedBy: true,
    isArchivedForMe: false,
    participants: {
        id: true,
        userId: true,
        userInfo: {
            userHandle: true,
            firstName: true,
            lastName: true,
            avatarUrl: true,
        },
    },
    latestMessage: {
        ...baseModel,
        channelId: true,
        replyToMessageId: true,
        channelMessageType: true,
        messageText: true,
        statuses: {
            userId: true,
            receivedAt: true,
            seenAt: true,
        },
        editedAt: true,
        suspendedAt: true,
        suspendedBy: true,
    },
};
const channelListItem = {
    ...baseModel,
    name: true,
    topic: true,
    description: true,
    tags: true,
    channelType: true,
    userIds: true,
    // metadata: {
    //   channelInvitationAccepted: true,
    //   messagesSentByCreatorCount: true,
    //   messagesSentByFirstParticipantCount: true,
    //   updatedAt: true,
    // },
    pausedAt: true,
    pausedBy: true,
    suspendedAt: true,
    suspendedBy: true,
    lockedAt: true,
    lockedBy: true,
    archivedAt: true,
    archivedBy: true,
    isArchivedForMe: false,
    participants: {
        id: true,
        userId: true,
        userInfo: {
            userHandle: true,
            firstName: true,
            lastName: true,
            avatarUrl: true,
        },
    },
    latestMessage: {
        ...baseModel,
        channelId: true,
        replyToMessageId: true,
        channelMessageType: true,
        messageText: true,
        statuses: {
            userId: true,
            receivedAt: true,
            seenAt: true,
        },
        editedAt: true,
        suspendedAt: true,
        suspendedBy: true,
    },
};
const channelInvitation = {
    ...baseModel,
    channelId: true,
    recipientId: true,
    channelName: true,
    channelTopic: true,
    messageText: true,
    declineReasonTextId: true,
    dismissedFromInboxBySenderAt: true,
    dismissedFromInboxByRecipientAt: true,
    readByRecipientAt: true,
    status: true,
    suspendedAt: true,
    suspendedBy: true,
    userSearchId: true,
    searchRank: true,
};
const channelMessage = {
    ...baseModel,
    adminNotes: true,
    channelId: true,
    replyToMessageId: true,
    channelMessageType: true,
    messageText: true,
    seq: true,
    // statuses: {
    //   userId: true,
    //   receivedAt: true,
    //   seenAt: true,
    // },
    editedAt: true,
    suspendedAt: true,
    suspendedBy: true,
};
const channelParticipant = {
    ...baseModel,
    userId: true,
    channelId: true,
    channelName: true,
    role: true,
    userInfo: {
        userHandle: true,
        firstName: true,
        lastName: true,
        avatarUrl: true,
    },
    lastReceivedSeq: true,
    lastSeenSeq: true,
    suspendedAt: true,
    suspendedBy: true,
    invitedBy: true,
};
const company = {
    ...baseModel,
    name: true,
    annualRevenue: true,
    companyStage: true,
    companyStageTextId: true,
    companyType: true,
    companyTypeTextId: true,
    description: true,
    employeeCount: true,
    foundedAt: true,
    industries: true,
    isFundraising: true,
    isOperational: true,
    location: true,
    metadata: true,
    userIds: true,
    websites: true,
};
const giftCardProduct = {
    ...baseModel,
    brandId: true,
    name: true,
    description: true,
    categories: true,
    slug: true,
    url: true,
    imageSourceFront: true,
    imageSourceBack: true,
    hasBarcode: true,
    barcodeFormat: true,
    genericGiftCardId: true,
    isGeneric: true,
    hasPin: true,
    termsEn: true,
    termsUrl: true,
    instructionsEn: true,
    instructionsUrl: true,
    denominations: {
        amount: true,
        enabled: true,
    },
};
const myUser = {
    ...baseModel,
    metadata: {
        updatedAt: true,
        totalTimeOnPlatform: true,
        channelsMetadata: {
            mentoringSessionCount: true,
        },
        groupsMetadata: {
            groupCount: true,
            updatedAt: true,
        },
    },
    firstName: true,
    lastName: true,
    userHandle: true,
    phoneNumber: true,
    phoneNumberUpdatedAt: true,
    isPhoneNumberVerified: true,
    email: true,
    emailUpdatedAt: true,
    isEmailVerified: true,
    emailSource: true,
    genderTextId: true,
    cityOfResidence: true,
    countryOfResidenceTextId: true,
    postalCode: true,
    avatarUrl: true,
    websites: {
        label: true,
        value: true,
        tags: true,
    },
    preferredLanguageTextId: true,
    spokenLanguagesTextIds: true,
    selectedUiLanguageTextId: true,
    discoverable: true,
    roles: true,
    appFeatures: true,
    source: true,
    timezone: true,
    preferences: {
        ...baseModel,
        shareEmail: true,
        sharePhoneNumber: true,
        showWelcomeMessage: true,
        notificationOptions: {
            notificationType: true,
            enableEmail: true,
            enableInAppMessage: true,
            enablePushNotification: true,
            enableSms: true,
            frequency: true,
        },
    },
    trustLevel: true,
    signedInAt: true,
    signedOutAt: true,
    latestActivityAt: true,
    userBlocks: {
        userId: true,
        reasonTextId: true,
        notes: true,
        createdAt: true,
    },
    inactivatedAt: true,
    inactivatedBy: true,
    termsAndConditionsAcceptedAt: true,
    optIntoNewsletter: true,
    onboardingStage: true,
    suspendedAt: true,
    suspendedBy: true,
    companyIds: true,
    groupIds: true,
    parentGroupIds: true,
    externalGroupIds: true,
    groupMemberships: {
        id: true,
        groupId: true,
        groupIdent: true,
        roles: true,
        userId: true,
    },
    seeksHelp: true,
    offersHelp: true,
    birthYear: true,
    educationLevelTextId: true,
    genderSelfDescribed: true,
    cityOfOrigin: true,
    isOnVacation: true,
    avatarAsset: {
        ...baseModel,
        ownerId: true,
        ownerModelType: true,
        assetType: true,
        hostingService: true,
        url: true,
        path: true,
        s3Bucket: true,
        s3Key: true,
        mimeType: true,
        uploadUrl: true,
        uploadUrlExpiresAt: true,
        uploadedAt: true,
        expiresAt: true,
    },
    fallbackUiLanguageTextId: true,
};
const productCategory = {
    ...baseModel,
    importId: true,
    name: true,
    labelEn: true,
    sortIndex: true,
};
const purchaseOrderItem = {
    ...baseModel,
    purchaseOrderId: true,
    productId: true,
    quantity: true,
    price: true,
    totalPrice: true,
};
const purchaseOrder = {
    ...baseModel,
    items: { ...purchaseOrderItem },
    userId: true,
    sumItemPrice: true,
    totalPrice: true,
    vat: true,
    paidAt: true,
    canceledAt: true,
    refundedAt: true,
};
const serviceRequest = {
    ...baseModel,
    adminNotes: true,
    deviceUuid: true,
    errorCode: true,
    events: {
        time: true,
        modelEventType: true,
        message: true,
    },
    expiresAt: true,
    finishedAt: true,
    message: true,
    messageIds: true,
    modelTypes: true,
    objectIds: true,
    result: true,
    serviceRequestType: true,
    source: true,
};
const shoppingCartItem = {
    ...baseModel,
    shoppingCartId: true,
    productId: true,
    quantity: true,
    price: true,
    totalPrice: true,
};
const shoppingCart = {
    ...baseModel,
    sumItemPrice: true,
    totalPrice: true,
    vat: true,
    items: { ...shoppingCartItem },
};
const sidMultiStepAction = {
    ...baseModel,
    adminNotes: true,
    actionStatus: true,
    actionType: true,
    attemptCount: true,
    confirmToken: true,
    deviceUuid: true,
    email: true,
    emailPassed: true,
    emailUpdatedAt: true,
    emailVerifiedAt: true,
    errors: {
        key: true,
        message: true,
        messageId: true,
    },
    events: {
        message: true,
        modelEventType: true,
        time: true,
    },
    expiresAt: true,
    notificationId: true,
    notificationMethod: true,
    notificationResult: true,
    notificationSentAt: true,
    password: true,
    passwordPassed: true,
    passwordResettedAt: true,
    passwordUpdatedAt: true,
    phoneNumber: true,
    phoneNumberPassed: true,
    phoneNumberUpdatedAt: true,
    phoneNumberVerifiedAt: true,
    report: true,
    result: true,
    signedInAt: true,
    textData: true,
    userHandle: true,
    userId: true,
    userIdent: true,
};
// SidMultiStepActionProgress is not a model that extends from BaseModel, so we don't add
// the BaseModel fields here.
const sidMultiStepActionProgress = {
    actionId: true,
    userId: true,
    actionType: true,
    actionStatus: true,
    notificationMethod: true,
    result: true,
    attemptCount: true,
    notificationSentAt: true,
    notificationResult: true,
    notificationId: true,
    textData: true,
    report: true,
    emailPassed: true,
    emailUpdatedAt: true,
    emailVerifiedAt: true,
    errors: {
        key: true,
        messageId: true,
        message: true,
    },
    authToken: true,
    authTokenExpiresAt: true,
    passwordPassed: true,
    passwordResettedAt: true,
    passwordUpdatedAt: true,
    phoneNumberPassed: true,
    phoneNumberUpdatedAt: true,
    phoneNumberVerifiedAt: true,
    signedInAt: true,
    expiresAt: true,
    events: {
        time: true,
        modelEventType: true,
        message: true,
    },
};
const user = {
    ...baseModel,
    firstName: true,
    lastName: true,
    userHandle: true,
    // genderTextId: true,
    // cityOfResidence: true,
    // countryOfResidenceTextId: true,
    // postalCode: true,
    avatarUrl: true,
    // websites: {
    //   label: true,
    //   value: true,
    //   tags: true,
    // },
    // preferredLanguageTextId: true,
    // spokenLanguagesTextIds: true,
    // selectedUiLanguageTextId: true,
    // discoverable: true,
    // roles: true,
    // appFeatures: true,
    // source: true,
    // timezone: true,
    // trustLevel: true,
    // latestActivityAt: true,
    // companyIds: true,
    // groupIds: true,
    // parentGroupIds: true,
    // externalGroupIds: true,
    // groupMemberships: {
    //   groupId: true,
    //   groupIdent: true,
    //   id: true,
    //   roles: true,
    //   userId: true,
    // },
    seeksHelp: true,
    offersHelp: true,
    // educationLevelTextId: true,
    // genderSelfDescribed: true,
    // cityOfOrigin: true,
    // isOnVacation: true,
    // fallbackUiLanguageTextId: true,
    // onboardingStage: true,
    // userBlocks: {
    //   userId: true,
    //   reasonTextId: true,
    //   notes: true,
    //   createdAt: true,
    // },
    inactivatedAt: true,
    inactivatedBy: true,
    suspendedAt: true,
    suspendedBy: true,
};
const userListItem = {
    id: true,
    firstName: true,
    lastName: true,
    userHandle: true,
    genderTextId: true,
    avatarUrl: true,
    websites: {
        label: true,
        value: true,
        tags: true,
    },
    preferredLanguageTextId: true,
    spokenLanguagesTextIds: true,
    countryOfResidenceTextId: true,
    regionOfResidence: true,
    cityOfResidence: true,
    timezone: true,
    seeksHelp: true,
    offersHelp: true,
    userBlocks: {
        userId: true,
        reasonTextId: true,
        notes: true,
        createdAt: true,
    },
    roles: true,
    trustLevel: true,
    latestActivityAt: true,
    createdAt: true,
    updatedAt: true,
};
const userInbox = {
    ...baseModel,
    userId: true,
    channels: {
        userId: true,
        unseenMessages: {
            id: true,
            channelId: true,
            replyToMessageId: true,
            channelMessageType: true,
            messageText: true,
            senderUserHandle: true,
            senderFirstName: true,
            senderLastName: true,
            senderAvatarUrl: true,
            seenAt: true,
            isArchived: true,
            createdAt: true,
            createdBy: true,
            updatedAt: true,
            updatedBy: true,
            userIds: true,
        },
        unseenArchivedMessages: {
            id: true,
            channelId: true,
            replyToMessageId: true,
            channelMessageType: true,
            messageText: true,
            senderUserHandle: true,
            senderFirstName: true,
            senderLastName: true,
            senderAvatarUrl: true,
            seenAt: true,
            isArchived: true,
            createdAt: true,
            createdBy: true,
            updatedAt: true,
            updatedBy: true,
            userIds: true,
        },
        unseenSystemMessages: {
            id: true,
            channelId: true,
            replyToMessageId: true,
            channelMessageType: true,
            messageText: true,
            senderUserHandle: true,
            senderFirstName: true,
            senderLastName: true,
            senderAvatarUrl: true,
            seenAt: true,
            isArchived: true,
            createdAt: true,
            createdBy: true,
            updatedAt: true,
            updatedBy: true,
            userIds: true,
        },
        latestMessages: {
            id: true,
            channelId: true,
            replyToMessageId: true,
            channelMessageType: true,
            messageText: true,
            senderUserHandle: true,
            senderFirstName: true,
            senderLastName: true,
            senderAvatarUrl: true,
            seenAt: true,
            isArchived: true,
            createdAt: true,
            createdBy: true,
            updatedAt: true,
            updatedBy: true,
            userIds: true,
        },
        latestArchivedMessages: {
            id: true,
            channelId: true,
            replyToMessageId: true,
            channelMessageType: true,
            messageText: true,
            senderUserHandle: true,
            senderFirstName: true,
            senderLastName: true,
            senderAvatarUrl: true,
            seenAt: true,
            isArchived: true,
            createdAt: true,
            createdBy: true,
            updatedAt: true,
            updatedBy: true,
            userIds: true,
        },
        pendingInvitations: {
            id: true,
            channelId: true,
            messageText: true,
            readByRecipientAt: true,
            status: true,
            createdAt: true,
            createdBy: true,
            recipientId: true,
        },
        invitations: {
            id: true,
            channelId: true,
            messageText: true,
            readByRecipientAt: true,
            status: true,
            createdAt: true,
            createdBy: true,
            recipientId: true,
        },
        itemIdHash: true,
        updatedAt: true,
        updatedBy: true,
    },
};
const brand = {
    ...baseModel,
    name: true,
    importId: true,
    imageSource: true,
    slug: true,
    url: true,
    balanceLookupUri: true,
    listed: true,
    logoImageSource: true,
    description: true,
    alias1: true,
    alias2: true,
    alias3: true,
};
const walletItem = {
    ...baseModel,
    walletId: true,
    productId: true,
    purchaseOrderItemId: true,
    brandId: true,
    productType: true,
    name: true,
    price: true,
    initialBalance: true,
    balance: true,
    code: true,
    hasBarcode: true,
    barcodeFormat: true,
    pin: true,
    source: true,
    imageSourceFront: true,
    imageSourceBack: true,
    referenceUrl: true,
    termsEn: true,
    termsUrl: true,
    instructionsEn: true,
    instructionsUrl: true,
    sortIndex: true,
    issuedAt: true,
    expiresAt: true,
    balanceUpdatedAt: true,
    transferStartedAt: true,
    transferAcceptedAt: true,
    archivedAt: true,
};
const wallet = {
    ...baseModel,
};
const walletItemTransfer = {
    ...baseModel,
    walletItemId: true,
    notificationId: true,
    recipientEmail: true,
    recipientFullName: true,
    subjectText: true,
    messageText: true,
    transferSlug: true,
    sentAt: true,
    acceptedAt: true,
    declinedAt: true,
    canceledAt: true,
    archivedAt: true,
    showOnline: true,
    recipientPhoneNumber: true,
};
const walletItemTransferRecipientInfo = {
    walletItem: { ...walletItem },
    walletItemTransfer: { ...walletItemTransfer },
    product: { ...giftCardProduct },
    brand: { ...brand },
};
const modelFields = {
    channel,
    channelInvitation,
    channelListItem,
    channelMessage,
    channelParticipant,
    company,
    giftCardProduct,
    myUser,
    productCategory,
    purchaseOrder,
    purchaseOrderItem,
    shoppingCart,
    shoppingCartItem,
    serviceRequest,
    sidMultiStepAction,
    sidMultiStepActionProgress,
    user,
    userInbox,
    userListItem,
    brand,
    wallet,
    walletItem,
    walletItemTransfer,
    walletItemTransferRecipientInfo,
};
export default modelFields;
//# sourceMappingURL=modelFields.js.map