const channel = {
    id: true,
    adminNotes: true,
    createdAt: true,
    createdBy: true,
    updatedAt: true,
    updatedBy: true,
    deletedAt: true,
    deletedBy: true,
    name: true,
    topic: true,
    description: true,
    tags: true,
    channelType: true,
    userIds: true,
    pausedAt: true,
    pausedBy: true,
    suspendedAt: true,
    suspendedBy: true,
    lockedAt: true,
    lockedBy: true,
    archivedAt: true,
    archivedBy: true,
    assumedMentorId: true,
    mm2Id: true,
    syncedWithMm2At: true,
    isArchivedForMe: false,
};
const channelInvitation = {
    id: true,
    adminNotes: true,
    createdAt: true,
    createdBy: true,
    updatedAt: true,
    updatedBy: true,
    deletedAt: true,
    deletedBy: true,
    channelId: true,
    recipientId: true,
    channelName: true,
    channelTopic: true,
    messageText: true,
    declineReasonTextId: true,
    dismissedFromInboxBySenderAt: true,
    dismissedFromInboxByRecipientAt: true,
    readByRecipientAt: true,
    status: true,
    suspendedAt: true,
    suspendedBy: true,
    userSearchId: true,
    searchRank: true,
};
const channelMessage = {
    id: true,
    adminNotes: true,
    createdAt: true,
    createdBy: true,
    updatedAt: true,
    updatedBy: true,
    deletedAt: true,
    deletedBy: true,
    channelId: true,
    replyToMessageId: true,
    channelMessageType: true,
    messageText: true,
    statuses: {
        userId: true,
        receivedAt: true,
        seenAt: true,
    },
    editedAt: true,
    suspendedAt: true,
    suspendedBy: true,
    mm2ConversationId: true,
    mm2Id: true,
    syncedWithMm2At: true,
};
const channelParticipant = {};
const myUser = {
    id: true,
    adminNotes: true,
    metadata: {
        updatedAt: true,
        totalTimeOnPlatform: true,
        channelsMetadata: {
            mentoringSessionCount: true,
        },
        groupsMetadata: {
            groupCount: true,
            updatedAt: true,
        },
    },
    createdAt: true,
    createdBy: true,
    updatedAt: true,
    updatedBy: true,
    deletedAt: true,
    deletedBy: true,
    firstName: true,
    lastName: true,
    userHandle: true,
    phoneNumber: true,
    phoneNumberUpdatedAt: true,
    isPhoneNumberVerified: true,
    email: true,
    emailUpdatedAt: true,
    isEmailVerified: true,
    emailSource: true,
    genderTextId: true,
    cityOfResidence: true,
    countryOfResidenceTextId: true,
    postalCode: true,
    avatarUrl: true,
    websites: {
        label: true,
        value: true,
        tags: true,
    },
    authType: true,
    tfaBackupCodes: true,
    passwordUpdatedAt: true,
    preferredLanguageTextId: true,
    spokenLanguagesTextIds: true,
    selectedUiLanguageTextId: true,
    discoverable: true,
    roles: true,
    appFeatures: true,
    source: true,
    timezone: true,
    preferences: {
        id: true,
        createdAt: true,
        createdBy: true,
        updatedAt: true,
        updatedBy: true,
        deletedAt: true,
        deletedBy: true,
        shareEmail: true,
        sharePhoneNumber: true,
        showWelcomeMessage: true,
        notificationOptions: {
            notificationType: true,
            enableEmail: true,
            enableInAppMessage: true,
            enablePushNotification: true,
            enableSms: true,
            frequency: true,
        },
    },
    trustLevel: true,
    signedInAt: true,
    signedOutAt: true,
    latestActivityAt: true,
    userBlocks: {
        userId: true,
        reasonTextId: true,
        notes: true,
        adminNotes: true,
        createdAt: true,
        syncedWithMm2At: true,
        mm2Id: true,
    },
    inactivatedAt: true,
    inactivatedBy: true,
    termsAndConditionsAcceptedAt: true,
    optIntoNewsletter: true,
    onboardingStage: true,
    suspendedAt: true,
    suspendedBy: true,
    companyIds: true,
    groupIds: true,
    parentGroupIds: true,
    externalGroupIds: true,
    groupMemberships: {
        groupId: true,
        groupIdent: true,
        id: true,
        roles: true,
        userId: true,
    },
    seeksHelp: true,
    offersHelp: true,
    birthYear: true,
    educationLevelTextId: true,
    genderSelfDescribed: true,
    cityOfOrigin: true,
    isOnVacation: true,
    avatarAsset: {
        id: true,
        adminNotes: true,
        createdAt: true,
        createdBy: true,
        updatedAt: true,
        updatedBy: true,
        deletedAt: true,
        deletedBy: true,
        ownerId: true,
        ownerModelType: true,
        assetType: true,
        hostingService: true,
        url: true,
        path: true,
        s3Bucket: true,
        s3Key: true,
        mimeType: true,
        uploadUrl: true,
        uploadUrlExpiresAt: true,
        uploadedAt: true,
        expiresAt: true,
    },
    fallbackUiLanguageTextId: true,
};
const sidMultiStepAction = {
    actionStatus: true,
    actionType: true,
    adminNotes: true,
    attemptCount: true,
    confirmToken: true,
    createdAt: true,
    createdBy: true,
    deletedAt: true,
    deletedBy: true,
    deviceUuid: true,
    email: true,
    emailPassed: true,
    emailUpdatedAt: true,
    emailVerifiedAt: true,
    errors: {
        adminNotes: true,
        createdAt: true,
        createdBy: true,
        deletedAt: true,
        deletedBy: true,
        events: true,
        id: true,
        key: true,
        message: true,
        messageId: true,
        metadata: true,
        updatedAt: true,
        updatedBy: true,
    },
    events: {
        message: true,
        modelEventType: true,
        time: true,
    },
    expiresAt: true,
    id: true,
    notificationId: true,
    notificationMethod: true,
    notificationResult: true,
    notificationSentAt: true,
    password: true,
    passwordPassed: true,
    passwordResettedAt: true,
    passwordUpdatedAt: true,
    phoneNumber: true,
    phoneNumberPassed: true,
    phoneNumberUpdatedAt: true,
    phoneNumberVerifiedAt: true,
    report: true,
    result: true,
    signedInAt: true,
    textData: true,
    tfaBackupCodes: true,
    updatedAt: true,
    updatedBy: true,
    userHandle: true,
    userId: true,
    userIdent: true,
};
const sidMultiStepActionProgress = {
    actionId: true,
    userId: true,
    actionType: true,
    actionStatus: true,
    notificationMethod: true,
    result: true,
    attemptCount: true,
    notificationSentAt: true,
    notificationResult: true,
    notificationId: true,
    textData: true,
    report: true,
    emailPassed: true,
    emailUpdatedAt: true,
    emailVerifiedAt: true,
    errors: {
        id: true,
        adminNotes: true,
        createdAt: true,
        createdBy: true,
        updatedAt: true,
        updatedBy: true,
        deletedAt: true,
        deletedBy: true,
        key: true,
        messageId: true,
        message: true,
    },
    authToken: true,
    authTokenExpiresAt: true,
    passwordPassed: true,
    passwordResettedAt: true,
    passwordUpdatedAt: true,
    phoneNumberPassed: true,
    phoneNumberUpdatedAt: true,
    phoneNumberVerifiedAt: true,
    signedInAt: true,
    expiresAt: true,
    events: {
        time: true,
        modelEventType: true,
        message: true,
    },
    createdAt: true,
    createdBy: true,
    updatedAt: true,
    updatedBy: true,
    deletedAt: true,
    deletedBy: true,
};
const user = {
    id: true,
    createdAt: true,
    createdBy: true,
    updatedAt: true,
    updatedBy: true,
    deletedAt: true,
    deletedBy: true,
    firstName: true,
    lastName: true,
    userHandle: true,
    genderTextId: true,
    cityOfResidence: true,
    countryOfResidenceTextId: true,
    postalCode: true,
    avatarUrl: true,
    websites: {
        label: true,
        value: true,
        tags: true,
    },
    preferredLanguageTextId: true,
    spokenLanguagesTextIds: true,
    selectedUiLanguageTextId: true,
    discoverable: true,
    roles: true,
    appFeatures: true,
    source: true,
    timezone: true,
    trustLevel: true,
    latestActivityAt: true,
    userBlocks: {
        userId: true,
        reasonTextId: true,
        notes: true,
        adminNotes: true,
        createdAt: true,
        syncedWithMm2At: true,
        mm2Id: true,
    },
    inactivatedAt: true,
    inactivatedBy: true,
    onboardingStage: true,
    suspendedAt: true,
    suspendedBy: true,
    companyIds: true,
    groupIds: true,
    parentGroupIds: true,
    externalGroupIds: true,
    groupMemberships: {
        groupId: true,
        groupIdent: true,
        id: true,
        roles: true,
        userId: true,
    },
    seeksHelp: true,
    offersHelp: true,
    educationLevelTextId: true,
    genderSelfDescribed: true,
    cityOfOrigin: true,
    isOnVacation: true,
    fallbackUiLanguageTextId: true,
};
const userInbox = {
    id: true,
    adminNotes: true,
    createdAt: true,
    createdBy: true,
    updatedAt: true,
    updatedBy: true,
    deletedAt: true,
    deletedBy: true,
    userId: true,
    channels: {
        userId: true,
        unseenMessages: {
            id: true,
            channelId: true,
            replyToMessageId: true,
            channelMessageType: true,
            messageText: true,
            senderUserHandle: true,
            senderFirstName: true,
            senderLastName: true,
            senderAvatarUrl: true,
            seenAt: true,
            isArchived: true,
            createdAt: true,
            createdBy: true,
            updatedAt: true,
            updatedBy: true,
            userIds: true,
        },
        unseenArchivedMessages: {
            id: true,
            channelId: true,
            replyToMessageId: true,
            channelMessageType: true,
            messageText: true,
            senderUserHandle: true,
            senderFirstName: true,
            senderLastName: true,
            senderAvatarUrl: true,
            seenAt: true,
            isArchived: true,
            createdAt: true,
            createdBy: true,
            updatedAt: true,
            updatedBy: true,
            userIds: true,
        },
        unseenSystemMessages: {
            id: true,
            channelId: true,
            replyToMessageId: true,
            channelMessageType: true,
            messageText: true,
            senderUserHandle: true,
            senderFirstName: true,
            senderLastName: true,
            senderAvatarUrl: true,
            seenAt: true,
            isArchived: true,
            createdAt: true,
            createdBy: true,
            updatedAt: true,
            updatedBy: true,
            userIds: true,
        },
        latestMessages: {
            id: true,
            channelId: true,
            replyToMessageId: true,
            channelMessageType: true,
            messageText: true,
            senderUserHandle: true,
            senderFirstName: true,
            senderLastName: true,
            senderAvatarUrl: true,
            seenAt: true,
            isArchived: true,
            createdAt: true,
            createdBy: true,
            updatedAt: true,
            updatedBy: true,
            userIds: true,
        },
        latestArchivedMessages: {
            id: true,
            channelId: true,
            replyToMessageId: true,
            channelMessageType: true,
            messageText: true,
            senderUserHandle: true,
            senderFirstName: true,
            senderLastName: true,
            senderAvatarUrl: true,
            seenAt: true,
            isArchived: true,
            createdAt: true,
            createdBy: true,
            updatedAt: true,
            updatedBy: true,
            userIds: true,
        },
        pendingInvitations: {
            id: true,
            channelId: true,
            messageText: true,
            readByRecipientAt: true,
            status: true,
            createdAt: true,
            createdBy: true,
            recipientId: true,
        },
        invitations: {
            id: true,
            channelId: true,
            messageText: true,
            readByRecipientAt: true,
            status: true,
            createdAt: true,
            createdBy: true,
            recipientId: true,
        },
        itemIdHash: true,
        updatedAt: true,
        updatedBy: true,
    },
};
const modelFields = {
    channel,
    channelInvitation,
    channelMessage,
    channelParticipant,
    sidMultiStepAction,
    sidMultiStepActionProgress,
    myUser,
    user,
    userInbox,
};
export default modelFields;
//# sourceMappingURL=modelFields.js.map