import { MultiStepActionError, MultiStepActionResult, MultiStepActionSendNotificationResult, MultiStepActionStatus, MultiStepActionType, NotificationMethod } from '../../fsdata/gql/graphql.js';
import { BaseModelMetadata } from './BaseModelMetadata.js';
export declare class SidMultiStepActionProgress {
    actionId: string;
    userId: string;
    actionType: MultiStepActionType;
    actionStatus?: MultiStepActionStatus | null;
    notificationMethod?: NotificationMethod | null;
    result: MultiStepActionResult;
    attemptCount: number;
    notificationSentAt?: Date | null;
    notificationResult?: MultiStepActionSendNotificationResult | null;
    notificationId?: string | null;
    textData?: string | null;
    report?: string | null;
    emailPassed?: boolean | null;
    emailUpdatedAt?: Date | null;
    emailVerifiedAt?: Date | null;
    errors?: MultiStepActionError[] | null;
    authToken?: string | null;
    authTokenExpiresAt?: Date | null;
    passwordPassed?: boolean | null;
    passwordResettedAt?: Date | null;
    passwordUpdatedAt?: Date | null;
    phoneNumberPassed?: boolean | null;
    phoneNumberUpdatedAt?: Date | null;
    phoneNumberVerifiedAt?: Date | null;
    signedInAt?: Date | null;
    expiresAt?: Date | null;
    metadata?: BaseModelMetadata | null;
    createdAt?: Date | null;
    createdBy?: string | null;
    updatedAt?: Date | null;
    updatedBy?: string | null;
    deletedAt?: Date | null;
    deletedBy?: string | null;
    constructor(attributes?: Partial<SidMultiStepActionProgress>);
}
