import { AppFeature, AuthType, UiLanguage, UserRole } from '../enums.js';
import { BaseModel } from "./BaseModel.js";
import { LabeledStringValue } from "./LabeledStringValue.js";
import { UserBlock } from './UserBlock';
export declare class User extends BaseModel {
    firstName?: string | null;
    lastName?: string | null;
    userHandle?: string | null;
    phoneNumber?: string | null;
    phoneNumberUpdatedAt?: Date | null;
    isPhoneNumberVerified: boolean;
    email?: string | null;
    emailUpdatedAt?: Date | null;
    isEmailVerified: boolean;
    emailSource?: string | null;
    genderTextId?: string | null;
    cityOfResidence?: string | null;
    regionOfResidence?: string | null;
    countryOfResidenceTextId?: string | null;
    postalCode?: string | null;
    avatarUrl?: string | null;
    websites?: LabeledStringValue[] | null;
    authType?: AuthType | null;
    passwordHash?: string | null;
    tfaBackupCodes?: string | null;
    passwordUpdatedAt?: Date | null;
    preferredLanguageTextId?: string | null;
    spokenLanguagesTextIds: string[];
    selectedUiLanguageTextId?: UiLanguage | null;
    fallbackUiLanguageTextId?: UiLanguage | null;
    discoverable?: boolean | null;
    roles: UserRole[];
    appFeatures?: AppFeature[] | null;
    source?: string | null;
    timezone?: string | null;
    trustLevel: number;
    signedInAt?: Date | null;
    signedOutAt?: Date | null;
    latestActivityAt?: Date | null;
    userBlocks?: UserBlock[] | null;
    inactivatedAt?: Date | null;
    inactivatedBy?: string | null;
    termsAndConditionsAcceptedAt?: Date | null;
    optIntoNewsletter?: boolean | null;
    onboardingStage?: string | null;
    suspendedAt?: Date | null;
    suspendedBy?: string | null;
    addedToBgVaultAt?: Date | null;
    isAdmin?: boolean;
    isTestUser?: boolean;
    emailLowerCase?: string | null;
    constructor(attributes?: Partial<User>);
}
